import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../report_problem/domain/entities/problem_report.dart';

/// Produces a branded, printable/shareable PDF for a single report —
/// the evidence document a citizen can hand to a local official or
/// carry to a complaint office. All values come directly from the
/// report's own recorded data; nothing is invented at export time.
class PdfReportGenerator {
  Future<Uint8List> generate(ProblemReport report) async {
    final doc = pw.Document();
    final dateFormat = DateFormat.yMMMMd().add_jm();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Darazinda Connect',
                        style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#0B5FA5'),
                        ),
                      ),
                      pw.Text(
                        'Tehsil Darazinda Slow Network — Connectivity '
                        'Evidence Report',
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                    ],
                  ),
                  pw.Text(
                    'Report ID\n${report.id}',
                    textAlign: pw.TextAlign.right,
                    style: pw.TextStyle(
                        fontSize: 11, fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
              pw.Divider(thickness: 1, color: PdfColor.fromHex('#E1E8EF')),
              pw.SizedBox(height: 12),
              pw.Text('Report Details',
                  style: pw.TextStyle(
                      fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              _kv('Category', report.category.label),
              _kv('Status', report.status.label),
              _kv('Submitted', dateFormat.format(report.createdAt)),
              _kv('Description', report.description ?? 'Not provided'),
              pw.SizedBox(height: 16),
              pw.Text('Location & Network Evidence',
                  style: pw.TextStyle(
                      fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              _kv('GPS Coordinates',
                  '${report.latitude.toStringAsFixed(6)}, '
                      '${report.longitude.toStringAsFixed(6)}'),
              _kv('Operator', report.operatorName ?? 'Not available on this device'),
              _kv('Network Type',
                  report.networkType ?? 'Not available on this device'),
              _kv('Linked Measurement ID',
                  report.linkedMeasurementId ?? 'None'),
              pw.SizedBox(height: 20),
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#F5F8FB'),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Text(
                  'This document is generated from data submitted by a '
                  'community member through Darazinda Connect. It is '
                  'evidence of a self-reported connectivity issue and '
                  'does not constitute an official finding by any '
                  'telecom operator or government authority unless '
                  'separately verified.',
                  style: const pw.TextStyle(fontSize: 9),
                ),
              ),
              pw.Spacer(),
              pw.Divider(color: PdfColor.fromHex('#E1E8EF')),
              pw.Text(
                'Generated by Darazinda Connect on '
                '${dateFormat.format(DateTime.now())}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  pw.Widget _kv(String key, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 150,
            child: pw.Text(key,
                style: const pw.TextStyle(
                    fontSize: 10, color: PdfColors.grey700)),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
          ),
        ],
      ),
    );
  }
}
